### ISSUE TITLE
 Change the repo to use glide instead of godep

### ISSUE THREAD

**Issue by songbinliu** [turbonomic/kubeturbo#109]
**Godep** is being used to manage the dependent packages. However, **Godep** is not easy to use, and always cause problems, especially the _kubernetes' client-go_ package.  It has been painful to update the dependency for kubetubo.

From a [comparison](https://github.com/Masterminds/glide/wiki/Go-Package-Manager-Comparison), **Glide** is becoming the best choice for package management now. In addition, Kubernetes is working on to [replace godep with glide](https://github.com/kubernetes/kubernetes/pull/24202).

**Comment by maxwangvmt** [comment]
Another option: [dep](https://github.com/golang/dep), which is recommended by godep for replacement.
