### ISSUE TITLE
Keep historic data for pods after actions

### ISSUE THREAD

**Issue by maxwangvmt** [turbonomic/kubeturbo#222]
Pods after resize and move actions will be renamed, resulting in losing the historic data.

We should identify the pods after actions and keep their historic data so we know the change before/after actions and the metric charts for the pod workload.

**Comment by enlinxu** [comment]
We need to understand better whether the persistency should be maintained at the individual pod/container level, or higher (deployment, service, statefulset etc.)

**Comment by esara** [comment]
resolving with containerspec in the container model
