### ISSUE TITLE
While deploying kubeturbo on openshift 3.11 getting protocol parsing error

### ISSUE THREAD

**Issue by rkharya** [turbonomic/kubeturbo#242]
turbonomics/CWOM - 2.1.1
kubeturbo image version - 6.0
Kubernetes - 1.11
OpenShift - 3.11

[root@ocp-hx-bastion kubeturbo-for-openshift]# oc logs kubeturbo
I0305 06:08:34.310269       1 kubeturbo_builder.go:205] spec path is: /etc/kubeturbo/config
I0305 06:08:34.310478       1 k8s_tap_service.go:33] K8sTapSericeSpec is: &{TurboCommunicationConfig:0xc420226d20 K8sTargetConfig:0xc42040f130}
I0305 06:08:34.312699       1 kubeturbo_builder.go:231] Finished creating turbo configuration: &{tapSpec:0xc420390220 broker:0xc42064ab00 Client:0xc4200b34a0 NodeQueue:0xc420161710 PodQueue:0xc4201617a0 ProbeConfig:0xc4203d6510 Recorder:<nil> k8sVersion:1.6.0 noneSchedulerName:turbo-none-exist-scheduler StopEverything:0xc42037d020}
I0305 06:08:34.314507       1 mediation_container.go:52] ---------- Created MediationContainer ----------
I0305 06:08:34.314537       1 remote_mediation_client.go:48] Created remote mediation client
I0305 06:08:34.314568       1 turbo_probe.go:61] [NewTurboProbe] Created TurboProbe: &{OpenShift CloudNative <nil> map[] <nil>}
I0305 06:08:34.314584       1 mediation_container.go:105] Registered CloudNative::OpenShift
I0305 06:08:34.314595       1 kubeturbo_builder.go:245] No leader election
I0305 06:08:34.314598       1 kubeturbo_service.go:52] ********** Start runnning Kubeturbo Service **********
I0305 06:08:34.314622       1 mediation_container.go:67] Initializing mediation container .....
I0305 06:08:34.314627       1 mediation_container.go:74] Registering 1 probes
I0305 06:08:34.317156       1 client_websocket_transport.go:230] [performWebSocketConnection]: wss://10.105.56.233:443/vmturbo/remoteMediation
I0305 06:08:34.339972       1 client_websocket_transport.go:275] [openWebSocketConn] created webSocket : wss://10.105.56.233:443/vmturbo/remoteMediation+v
I0305 06:08:34.339988       1 client_websocket_transport.go:243] [performWebSocketConnection]*********** Connected to server wss://10.105.56.233:443/vmturbo/remoteMediation::http://127.0.0.1
I0305 06:08:34.339992       1 client_websocket_transport.go:244] WebSocket transport layer is ready.
I0305 06:08:34.339998       1 client_websocket_transport.go:138] [ListenForMessages] 2019-03-05 06:08:34.339997018 +0000 UTC : ENTER
I0305 06:08:34.340013       1 remote_mediation_client.go:90] Start sdk client protocol ........
I0305 06:08:34.340027       1 sdk_client_protocol.go:25] Starting Protocol Negotiation ....
I0305 06:08:34.340037       1 sdk_client_protocol.go:54] Send negotiation message: protocol_version:"5.9.0"
I0305 06:08:34.340106       1 client_websocket_transport.go:155] [ListenForMessages]: connected, waiting for server response ...
I0305 06:08:34.340120       1 client_protobuf_endpoint.go:36] Created Protobuf Endpoint NegotiationEndpoint
I0305 06:08:34.342611       1 client_websocket_transport.go:176] [ListenForMessages] received message on websocket
I0305 06:08:34.342634       1 client_websocket_transport.go:155] [ListenForMessages]: connected, waiting for server response ...
E0305 06:08:34.342644       1 client_websocket_transport.go:162] [ListenForMessages] received EOF on websocket EOF
E0305 06:08:34.342649       1 client_websocket_transport.go:165] [ListenForMessages] error during receive EOF
I0305 06:08:34.342663       1 protobuf_endpoint.go:79] ParsingBProtocol version "5.9.0" is not allowed to communicate with server
I0305 06:08:34.342713       1 sdk_client_protocol.go:72] [NegotiationEndpoint] : Received: &{ServerMsg:{MediationServerMessage:<nil> MessageID:<nil> XXX_unrecognized:[]} NegotiationMsg:{NegotiationResult:REJECTED Description:0xc4203d2080 XXX_unrecognized:[]} RegistrationMsg:{XXX_unrecognized:[]}}
E0305 06:08:34.342739       1 sdk_client_protocol.go:85] Protocol version negotiation failed%!(EXTRA string=REJECTED) :Protocol version "5.9.0" is not allowed to communicate with server)
E0305 06:08:34.342743       1 sdk_client_protocol.go:29] Failure during Protocol Negotiation, Registration message will not be sent
E0305 06:08:34.342748       1 remote_mediation_client.go:99] Registration with server failed
F0305 06:08:34.342825       1 tap_service.go:42] Probe CloudNative::OpenShift is not registered

config -

{
        "communicationConfig": {
                "serverMeta": {
                        "turboServer": "https://10.105.56.233:443"
                },
                "restAPIConfig": {
                        "opsManagerUserName": "administrator",
                        "opsManagerPassword": "Nbv12345!"
                }
        },
        "targetConfig": {
                "probeCategory":"CloudNative",
                "targetType":"OpenShift",
                "address":"https://10.105.56.234:8443",
                "username":"admin",
                "password":"Nbv12345!"
        }
}

kubetrubo-openshift.yaml -

apiVersion: v1
kind: Pod
metadata:
  name: kubeturbo
  labels:
    name: kubeturbo
spec:
  nodeSelector:
    role: master
  containers:
  - name: kubeturbo
    image: vmturbo/kubeturbo:6.0
    command:
      - /bin/kubeturbo
    args:
      - --v=3
      - --kubeconfig=/etc/kubeturbo/admin.kubeconfig
      - --turboconfig=/etc/kubeturbo/config
      - --cadvisor-port=9999
    volumeMounts:
    - name: vmt-config
      mountPath: /etc/kubeturbo
      readOnly: true
  volumes:
  - name: vmt-config
    hostPath:
      path: /etc/kubeturbo
  restartPolicy: Always

Appreciate if someone help in debugging this?

**Comment by enlinxu** [comment]
Thanks @rkharya for trying Kubeturbo.
I noticed that you seem to use some outdated instruction to deploy kubeturbo, would you please refer to https://github.com/turbonomic/kubeturbo/tree/master/deploy ?

Please also make sure that you are using the right TURBONOMIC_SERVER_VERSION in server Metadata in the configmap yaml. If you are using CWOM 2.1.1, you should use 6.2.7 in that field.

Please let me know how it works.

**Comment by rkharya** [comment]
Tried out with instruction set@https://github.com/turbonomic/kubeturbo/tree/master/deploy, ending up with similar protocol version error -

[root@ocp-hx-bastion kubeturbo-for-openshift]# oc logs kubeturbo-649c74f67d-s54cx
I0306 05:30:22.295821       1 kubeturbo.go:49] Run Kubeturbo service (GIT_COMMIT: d6a2df2bc70922964c5ad9af43e780a952d27a6f)
W0306 05:30:22.296148       1 kubeturbo_builder.go:175] Neither --kubeconfig nor --master was specified.  Using default API client.  This might not work.
W0306 05:30:22.296384       1 client_config.go:529] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
I0306 05:30:22.305699       1 kubeturbo_builder.go:317] Kubernetes version: {
  "major": "1",
  "minor": "11+",
  "gitVersion": "v1.11.0+d4cacc0",
  "gitCommit": "d4cacc0",
  "gitTreeState": "clean",
  "buildDate": "2019-01-14T00:24:11Z",
  "goVersion": "go1.10.3",
  "compiler": "gc",
  "platform": "linux/amd64"
}
I0306 05:30:22.306162       1 kubeturbo_builder.go:321] Openshift version: {
  "major": "3",
  "minor": "11+",
  "gitVersion": "v3.11.69",
  "gitCommit": "7478b86cf2",
  "gitTreeState": "",
  "buildDate": "2019-01-14T00:24:11Z",
  "goVersion": "",
  "compiler": "",
  "platform": ""
}
I0306 05:30:22.306178       1 kubeturbo_builder.go:215] Openshift cluster? true
I0306 05:30:22.306413       1 mediation_container.go:52] ---------- Created MediationContainer ----------
I0306 05:30:22.306449       1 remote_mediation_client.go:48] Created remote mediation client
I0306 05:30:22.555363       1 turbo_probe.go:76] [NewTurboProbe] Created TurboProbe: &{%!s(*probe.ProbeConfig=&{Kubernetes-1305354412 Cloud Native 0xc420364a20}) %!s(*probe.ProbeRegistrationAgent=&{<nil> <nil> <nil> <nil>}) map[] <nil>}
I0306 05:30:22.555402       1 mediation_container.go:105] Registered Cloud Native::Kubernetes-1305354412
I0306 05:30:22.555415       1 kubeturbo_builder.go:252] No leader election
I0306 05:30:22.555420       1 kubeturbo_builder.go:254] ********** Start runnning Kubeturbo Service **********
I0306 05:30:22.555533       1 mediation_container.go:67] Initializing mediation container .....
I0306 05:30:22.555541       1 mediation_container.go:74] Registering 1 probes
I0306 05:30:22.555558       1 client_websocket_transport.go:276] [performWebSocketConnection]: wss://10.105.56.233:443/vmturbo/remoteMediation
I0306 05:30:22.565009       1 client_websocket_transport.go:291] [performWebSocketConnection]*********** Connected to server 10.105.56.233:443::172.31.2.81:43854
I0306 05:30:22.565023       1 client_websocket_transport.go:292] WebSocket transport layer is ready.
I0306 05:30:22.565034       1 remote_mediation_client.go:90] Start sdk client protocol ........
I0306 05:30:22.565053       1 sdk_client_protocol.go:31] Starting Protocol Negotiation ....
I0306 05:30:22.565140       1 client_websocket_transport.go:195] [ListenForMessages]: connected, waiting for server response ...
I0306 05:30:22.567202       1 client_websocket_transport.go:195] [ListenForMessages]: connected, waiting for server response ...
I0306 05:30:22.567222       1 protobuf_endpoint.go:79] ParsingBProtocol version "6.2.7" is not allowed to communicate with server
E0306 05:30:22.567258       1 sdk_client_protocol.go:110] Protocol version negotiation failed REJECTED) :Protocol version "6.2.7" is not allowed to communicate with server
E0306 05:30:22.568400       1 sdk_client_protocol.go:35] Failure during Protocol Negotiation, Registration message will not be sent
E0306 05:30:22.568417       1 remote_mediation_client.go:99] Registration with server failed
I0306 05:30:22.568425       1 client_websocket_transport.go:126] Begin to send websocket Close frame.
E0306 05:30:22.567916       1 client_websocket_transport.go:212] [ListenForMessages] error during receive websocket: close 1001 (going away): WebsocketServerTransport[/vmturbo/remoteMediation-124] shut down
panic: send on closed channel

goroutine 25 [running]:
github.com/turbonomic/kubeturbo/vendor/github.com/turbonomic/turbo-go-sdk/pkg/mediationcontainer.(*ClientWebSocketTransport).stopListenForMessages(0xc42026e460)
	/root/dev/go/src/github.com/turbonomic/kubeturbo/vendor/github.com/turbonomic/turbo-go-sdk/pkg/mediationcontainer/client_websocket_transport.go:168 +0xcd
github.com/turbonomic/kubeturbo/vendor/github.com/turbonomic/turbo-go-sdk/pkg/mediationcontainer.(*ClientWebSocketTransport).ListenForMessages(0xc42026e460)
	/root/dev/go/src/github.com/turbonomic/kubeturbo/vendor/github.com/turbonomic/turbo-go-sdk/pkg/mediationcontainer/client_websocket_transport.go:215 +0x6e3
created by github.com/turbonomic/kubeturbo/vendor/github.com/turbonomic/turbo-go-sdk/pkg/mediationcontainer.(*ClientWebSocketTransport).Connect
	/root/dev/go/src/github.com/turbonomic/kubeturbo/vendor/github.com/turbonomic/turbo-go-sdk/pkg/mediationcontainer/client_websocket_transport.go:93 +0x1fb

Here is the configmap details -

[root@ocp-hx-bastion kubeturbo-for-openshift]# oc get configmap/turbo-config -o yaml
apiVersion: v1
data:
  turbo.config: |-
    {
        "communicationConfig": {
            "serverMeta": {
                "version": "6.2.7",
                "turboServer": "https://10.105.56.233"
            },
            "restAPIConfig": {
                "opsManagerUserName": "administrator",
                "opsManagerPassword": "Nbv12345!"
            }
        },
        "targetConfig": {
            "targetName":"OpenShift"
        }
    }
kind: ConfigMap
metadata:
  creationTimestamp: 2019-03-06T04:48:18Z
  name: turbo-config
  namespace: default
  resourceVersion: "7599820"
  selfLink: /api/v1/namespaces/default/configmaps/turbo-config
  uid: 0f85063b-3fcb-11e9-a08f-005056820894

And the kubeturbo deployment yaml -

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kubeturbo
  namespace: default
  labels:
    app: kubeturbo
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        kubeturbo.io/controllable: "false"
      labels:
        app: kubeturbo
    spec:
      serviceAccount: turbo-user
      containers:
        - name: kubeturbo
          # Replace the image with desired version
          image: vmturbo/kubeturbo:6.2
          imagePullPolicy: IfNotPresent
          args:
            - --v=2
            - --turboconfig=/etc/kubeturbo/turbo.config
            #- --kubeconfig=/etc/kubeturbo/admin.kubeconfig
            #- --cadvisor-port=9999
            # Comment out the following two args if running k8s 1.10 or older
            #- --kubelet-https=true
            #- --kubelet-port=10250
            # Uncomment the following arg if using IP for stitching
            #- --stitch-uuid=false
          volumeMounts:
          - name: turbo-volume
            mountPath: /etc/kubeturbo
            readOnly: true
      volumes:
      - name: turbo-volume
        configMap:
          name: turbo-config
      restartPolicy: Always

Let me know if you need any other de-bug/log outputs, happy to help in fixing this.

**Comment by enlinxu** [comment]
@rkharya  Thanks for trying. If you have the ssh access to the CWOM, would you please check the output of : ls -al /srv/tomcat/webapps/vmturbo/WEB-INF/lib/com.vmturbo.platform-*

If you see: -rw-r--r--. 1 tomcat tomcat 10119486 Feb 16 15:27 /srv/tomcat/webapps/vmturbo/WEB-INF/lib/com.vmturbo.platform-6.3.0.jar

Then the version should be 6.3.0.

If you see something like: -rw-r--r--. 1 tomcat tomcat 10119486 Feb 16 15:27 /srv/tomcat/webapps/vmturbo/WEB-INF/lib/com.vmturbo.platform-6.3.0-SNAPSHOT.jar

Then the version should be 6.3.0-SNAPSHOT.

The version negotiation is there to guarantee the protobuf consistency.

**Comment by rkharya** [comment]
6.2.7.1-SNAPSHOT - version helped starting the kubeturbo pod. But looks like its not working as expected. There are 2 initial observations noted -

1. CWOM dashboard a have Kubernetes target validation failure messages
2. There are several errors being reported on the logs with kubeturbo pod

Both these error log files are attached herewith. Let me know how to move forward on this.

<img width="605" alt="screenshot 2019-03-07 at 9 42 37 am" src="https://user-images.githubusercontent.com/12057795/53931958-62acd000-40bd-11e9-8a7b-dcf3806bfa35.png">
<img width="1356" alt="screenshot 2019-03-07 at 9 42 21 am" src="https://user-images.githubusercontent.com/12057795/53931959-62acd000-40bd-11e9-84d1-626aaa1990e9.png">
[kubeturbo-log.txt](https://github.com/turbonomic/kubeturbo/files/2939462/kubeturbo-log.txt)

**Comment by rkharya** [comment]
[kubeturbo-log.txt](https://github.com/turbonomic/kubeturbo/files/2939471/kubeturbo-log.txt)

**Comment by enlinxu** [comment]
@rkharya In the Kubeturbo yaml, seems like you are using 10255 to access the kubelet. In openshift or k8s 1.10+, they are using 10250 as the port, please refer to: https://github.com/turbonomic/kubeturbo/blob/master/deploy/kubeturbo_yamls/YAMLS_README.md

 - --kubelet-https=true
 - --kubelet-port=10250

You can edit the deployment and restart kubeturbo pod

**Comment by rkharya** [comment]
@enlinxu My bad, took the comment other way round. Thanks for all your help. Am good to explore and deep dive.
