### ISSUE TITLE
how am I supposed to set server in openshift?

### ISSUE THREAD

**Issue by dongwangdw** [turbonomic/kubeturbo#574]
I deployed the operator in OCP.
But not sure how to setup the server link.

The ingress should be exposed by route in OCP based on a named service.
What should I set it now with kubeturbo?

**Comment by esara** [comment]
@dongwangdw kubeturbo (deployed in each managed cluster) is intended to communicate with the Turbonomic Platform deployed on a management cluster using https://catalog.redhat.com/software/operators/detail/5ec3fa51110f56bd24f2dd59
The turbonomic platform operator can create the route (once) that will be used by each kubeturbo instance in the managed clusters. More details about the platform deployment are https://github.com/turbonomic/t8c-install/wiki

**Comment by dongwangdw** [comment]
@esara 
Thanks you for clearing my confusion of basic concpets.
I have installed the operator in my OCP. 

I install the XI CR sequentially. Well, all the pods are pending:
```
action-orchestrator-f9c56c58f-pvq8k   0/1     Running   0          72s
clustermgr-d59959849-tgklc            0/1     Running   0          72s
cost-6f887f8dc8-q2qxq                 0/1     Running   0          72s
group-6b9848974c-695f6                0/1     Running   0          72s
history-5f779cf4f-mrc4t               0/1     Running   0          72s
market-74cbcd8659-bqxxc               0/1     Running   0          72s
plan-orchestrator-6bd97f56cb-zntz8    0/1     Running   0          72s
repository-788bd84f96-4r78c           0/1     Running   0          72s
```

I describe one of them and found that Liveness/Readiness probe are failed due to ```connect: connection refused```

Did I missed anything ?
or should I deploy the operator with some kind of license provided?

**Comment by esara** [comment]
it appears that you either do not have a default storage class / did not provide a storage class in the cr / or your persistent volumes are not provisionined (oc get pvc) please see https://github.com/turbonomic/t8c-install/wiki/Storage-Class-Requirements or contact our tech support at https://support.turbonomic.com/ - this is not a kubeturbo issue, but happy to help either way.

**Comment by dongwangdw** [comment]
I do have the default storage class.
And all the PVCs are bound.

```
NAME                   STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
api                    Bound    pvc-bbb11a8c-718e-4126-a882-408c907af77f   1Gi        RWO            csi-cephfs     22h
api-certs              Bound    pvc-b9346c06-5443-41a9-8c28-65fb98644969   1Gi        RWO            csi-cephfs     22h
arangodb               Bound    pvc-ec914188-129f-462d-ada8-15b6fed4ec4d   100Gi      RWO            csi-cephfs     22h
arangodb-apps          Bound    pvc-9fa641ec-5d9a-4527-ba1d-1df5044a92f0   2Gi        RWO            csi-cephfs     22h
arangodb-dump          Bound    pvc-a93404b6-6a9f-4a74-8ffd-8d974c747392   2Gi        RWO            csi-cephfs     22h
auth                   Bound    pvc-063c246a-a051-484e-9146-d98e412b92ca   1Gi        RWO            csi-cephfs     22h
consul-data            Bound    pvc-af1b6b5f-94c7-4db8-bb22-a767be893dac   1Gi        RWO            csi-cephfs     22h
db-data                Bound    pvc-746b6b40-1175-482b-8141-4341d03f5d97   500Gi      RWO            csi-cephfs     22h
kafka-log              Bound    pvc-7b73b831-0cda-49c0-bac0-7f9117410e18   50Gi       RWO            csi-cephfs     22h
rsyslog-auditlogdata   Bound    pvc-27f2a924-5326-4e1a-a4dd-18b694c2c501   30Gi       RWO            csi-cephfs     22h
rsyslog-syslogdata     Bound    pvc-c00f6f87-6c02-4b47-ac50-a0ceccb82885   30Gi       RWO            csi-cephfs     22h
topology-processor     Bound    pvc-46c6dc70-7bc3-433b-b144-62c5451b1b04   3Gi        RWO            csi-cephfs     22h
zookeeper-data         Bound    pvc-d04713f7-2d32-424b-b644-9c517acaaad5   3Gi        RWO            csi-cephfs     22h
```

And I found it is a SC issue.
```
pods "db-589bd876b4-" is forbidden: unable to validate against any security context constraint: [provider            2    restricted: .spec.securityContext.fsGroup: Invalid value: []int64{2000}: 2000 is not an allowed group]
```

```
.....
       securityContext:
         fsGroup: 2000
....
```

**Comment by dongwangdw** [comment]
I just gave the default service account in the namespace priviledged. And all the pods just returned.
I think this should not happen here.

But it seems the ngnix is used for the ingress whose service type is loadbalancer pending.
And now no route was created. So I can not get access to the UI now. 

And for the platform operator. I found three from operatorHub.
![Screen Shot 2021-07-13 at 4 24 41 PM](https://user-images.githubusercontent.com/2303377/125418173-19d662cd-b29c-47f4-8260-c59040e967f6.png)

I installed the community one whose version is 8.1.0.

**Comment by dongwangdw** [comment]
It worked.
@esara Thanks for your support. I wil close this.

**Comment by esara** [comment]
@dongwangdw no problem at all, happy to help.
The xl CR is selfdocumented using openapispecv3, which you can navigate through the openshift console (when creating a new operand), or you can see the actual options under
https://github.com/turbonomic/t8c-install/blob/master/operator/config/crd/bases/charts.helm.k8s.io_xls.yaml

regarding managing your private and openshift clusters using the Turbonomic platform, we are back to your original starting point, you need to deploy kubeturbo in each cluster and point them to the same server url.
While this can be done one by one, you can also automate this using RACM, an example config posted at
https://github.com/turbonomic/kubeturbo/blob/master/deploy/kubeturbo-racm/kubeturbo_application.yaml

**Comment by dongwangdw** [comment]
@esara Great!!
Thanks so much for your excellent support.
