### ISSUE TITLE
Kubeturbo Operator's CRD requires update to apiextensions version to support k8s 1.22+

### ISSUE THREAD

**Issue by evat-pm** [turbonomic/kubeturbo#603]
The CRD for the operator uses apiVersion: apiextensions.k8s.io/v1beta1 and this is officially deprecated in k8s 1.22
https://kubernetes.io/docs/reference/using-api/deprecation-guide/#customresourcedefinition-v122.

This will cause this CRD are related operator to not deploy into any kubernetes cluster v1.22 or higher.

Need to update the apiextensions to v1 and update related schema, validations.

**Comment by esara** [comment]
duplicate of https://github.com/turbonomic/kubeturbo/issues/597
