### ISSUE TITLE
Failed to resize workload controller

### ISSUE THREAD

**Issue by YJChan** [turbonomic/kubeturbo#611]
Hi, 
I've trying around with turbonomic on my openshift cluster. I've deployed the turbonomic thru operator hub and enabled kubeturbo. 
When I try to apply one of the action to resize my pod memory limits, I received the following errors in kubeturbo logs:
```
failed after 3 attempts, last error: operatorResourceSpec not found in operatorResourceSpecMap for operatorCR xxxx-xxxx-xxx-xxxxxx (uuid)
```
I'm trying to understand what is this error about and what are the possible solution.

Kubeturbo version: 8.2.5
Turbonomic Platform Operator: v42.1.0

Appreacite your help. Thanks

**Comment by enlinxu** [comment]
@YJChan Thanks for trying. Looks like the workload you are trying to resize is controlled and managed by Operator. When the application lifecycle is managed by Operator, any Turbo action directly applied to the deployment will be reverted by the Operator. 
To make it work properly, we have another project, https://github.com/turbonomic/orm , to allow user create a map from Deployment to the Custom Resource that the operator is managing, you can find some samples here, https://github.com/turbonomic/orm/tree/master/config/samples .

**Comment by YJChan** [comment]
Hi @enlinxu , Thank you for clarifying this. 
I managed to get it work by following the sample.
