### ISSUE TITLE
[Openshift] Without kubernetes cert files, cannot access kubelet info.

### ISSUE THREAD

**Issue by songbinliu** [turbonomic/kubeturbo#87]
The [new discovery framework](https://github.com/turbonomic/kubeturbo/commit/99ac3d678f357689e0293c96711bcf2615dc6a37) gets resource usage from Kubelet, instead of cAdvisor.  

Previously,  when deploying kubeturbo, we can either specify  **--master** or **--kubeconfig** parameter.  But for Openshift (v3.4) cluster, if we specify **--master*, the internal [kubeletClient](https://github.com/turbonomic/kubeturbo/blob/master/pkg/discovery/monitoring/kubelet/kubelet_client.go) won't be able to get monitor information from kubelet.

**Comment by songbinliu** [comment]
I test with a small tool--[kubeletMonitor](https://github.com/songbinliu/kubeletMonitor):
    For a standard Kubernetes cluster (version 1.7), if only specify **--master** parameter,  I can get node information, and node hosting entities usage.

    For a Openshift cluster (version 3.4),  if only specify **--master** parameter,  I cannot get the monitor information, and the error is: 
    ```console
 403-"403 Forbidden", body: Forbidden (reason=User "system:anonymous" cannot get nodes/stats at the cluster scope, user=system:anonymous, verb=get, namespace=, resource=nodes)
   ```

**Comment by DongyiYang** [comment]
> For a standard Kubernetes cluster (version 1.7), if only specify --master parameter, I can get node monitor information.

basically, if the K8s API server runs on HTTP, then you can use --master. If runs on HTTPs, certificates are always needed to visit API server, which are inside kubeconfig.

**Comment by songbinliu** [comment]
Right. Seems OpenShift's Kubelet monitor information can only be accessed by HTTPS, and standard Kubernetes' Kubelete monitor information can only be accessed via HTTP.  So we need to specify the kubeconfig to get the certificates.

By the way, I refactored the KubeletClient, so that Resize action executor can use it to get Node cpu frequency. Please help review it if possible. @DongyiYang  https://github.com/turbonomic/kubeturbo/pull/88
